// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGh0fu0GcMX1pL6B4hg702vgZ_b_YXio',
    appId: '1:1031776267722:web:8d6aae8ab41606391db333',
    messagingSenderId: '1031776267722',
    projectId: 'sportsitemdonationp',
    authDomain: 'sportsitemdonationp.firebaseapp.com',
    storageBucket: 'sportsitemdonationp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaxJGST65IcWiI7oHOpp4LUVc1g0I1A8',
    appId: '1:1031776267722:android:e769917035156d8d1db333',
    messagingSenderId: '1031776267722',
    projectId: 'sportsitemdonationp',
    storageBucket: 'sportsitemdonationp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3Gu5QSFtUAQZ8BMRZFeIV5WtQXFrNSI',
    appId: '1:1031776267722:ios:6b1bf7bba21bf25f1db333',
    messagingSenderId: '1031776267722',
    projectId: 'sportsitemdonationp',
    storageBucket: 'sportsitemdonationp.appspot.com',
    iosBundleId: 'com.example.sportsdonationapp',
  );
}
